import type { Metadata } from "next";
import { orbitron, outfit } from "@/lib/font";
import "./globals.css";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Task Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${outfit.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
